import Header from "./components/Header";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "This is Todo App",
  description: "Generated by This is Todo App",
};
import { UserContextProvider } from "./context/UserContext";
import { ToastContainer } from "react-toastify";
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UserContextProvider>
          <ToastContainer />
          <Header />
          {children}
        </UserContextProvider>
      </body>
    </html>
  );
}
